# Railway deployment configuration for backend

[build]
  command = "npm install --production=false"

[deploy]
  startCommand = "npm start"
  healthcheckPath = "/health"
  healthcheckTimeout = 300
  restartPolicyType = "on_failure"

[env]
  NODE_ENV = "production"
  # PORT is automatically injected by Railway
  # Add your environment variables in Railway dashboard:
  # NETLIFY_SITE_URL = "https://your-site.netlify.app"
  # JWT_SECRET = "your-secret-key"
  # DB_URL = "${{Postgres.DATABASE_URL}}" (if using Railway Postgres)
